import { TICKS_PER_SECOND } from "./constants";
import type {
  ClassDefinition,
  EnemyKind,
  HeroClassId,
  OptionFlavor,
  PassiveDefinition,
  PassiveId,
  WeaponDefinition,
  WeaponId,
} from "./types";

export const heroClassIds: readonly HeroClassId[] = [
  "fighter",
  "knight",
  "berserker",
  "dwarf",
  "paladin",
  "mage",
  "priest",
  "warlock",
  "elf",
  "thief",
  "monk",
];

export const weaponIds: readonly WeaponId[] = [
  "swordSweep",
  "fireBolt",
  "holyBolt",
  "throwingAxe",
  "frostNova",
  "garlicAura",
  "holySmash",
  "lifeDrain",
  "shadowDaggers",
  "earthShatter",
  "magicArrow",
  "whirlwindAxe",
  "shieldBash",
  "radiantBurst",
  "meteor",
  "chainLightning",
  "poisonFlask",
  "crossbowBolt",
];

export const passiveIds: readonly PassiveId[] = ["maxHp", "speed", "damage", "magnet", "gold"];

/**
 * Roster v3 baselines (docs/roster-v3.md).
 * strength/weakness are honest card copy — selection is a tradeoff.
 */
export const classDefinitions: Record<HeroClassId, ClassDefinition> = {
  fighter: {
    id: "fighter",
    name: "Fighter",
    maxHp: 110,
    speed: 95,
    startingWeapon: "swordSweep",
    affinityWeapons: ["swordSweep", "whirlwindAxe", "shieldBash", "crossbowBolt", "throwingAxe"],
    color: "#c4a46a",
    glyph: "F",
    strength: "Reliable master-at-arms — steady damage every fight",
    weakness: "No signature tricks; never the best at any one job",
  },
  knight: {
    id: "knight",
    name: "Knight",
    maxHp: 140,
    speed: 85,
    startingWeapon: "swordSweep",
    affinityWeapons: ["swordSweep", "shieldBash", "holySmash", "garlicAura"],
    color: "#d9a441",
    glyph: "K",
    strength: "Immovable bulwark — highest HP, shrugs contact hits",
    weakness: "Lowest attack tier; slow feet, no burst",
  },
  berserker: {
    id: "berserker",
    name: "Berserker",
    maxHp: 80,
    speed: 100,
    startingWeapon: "swordSweep",
    affinityWeapons: ["swordSweep", "whirlwindAxe", "throwingAxe", "garlicAura"],
    color: "#d45a43",
    glyph: "B",
    strength: "Blood-fueled whirlwind — kills restore HP",
    weakness: "Glass jaw; fatigue after 90s drains the fury",
  },
  dwarf: {
    id: "dwarf",
    name: "Dwarf",
    maxHp: 120,
    speed: 90,
    startingWeapon: "swordSweep",
    affinityWeapons: ["swordSweep", "earthShatter", "throwingAxe", "shieldBash"],
    color: "#b8895a",
    glyph: "D",
    strength: "Stout tunnel-fighter — small hitbox, quick weapon cadence",
    weakness: "Short reach fantasy; no real ranged peak",
  },
  paladin: {
    id: "paladin",
    name: "Paladin",
    maxHp: 125,
    speed: 88,
    startingWeapon: "swordSweep",
    startingWeapons: ["swordSweep"],
    affinityWeapons: ["swordSweep", "holySmash", "holyBolt", "radiantBurst", "shieldBash"],
    color: "#e8d48a",
    glyph: "A",
    strength: "Holy protector — tanky enough and mends (+2 HP / 5s)",
    weakness: "Heals worse than Priest; softer than Knight; no peak damage",
  },
  mage: {
    id: "mage",
    name: "Mage",
    maxHp: 70,
    speed: 100,
    startingWeapon: "fireBolt",
    affinityWeapons: ["fireBolt", "meteor", "chainLightning", "frostNova", "magicArrow"],
    color: "#7aa5ff",
    glyph: "M",
    strength: "Arcane artillery — highest burst damage",
    weakness: "Dies to a stiff breeze (lowest HP)",
  },
  priest: {
    id: "priest",
    name: "Priest",
    maxHp: 95,
    speed: 95,
    startingWeapon: "holyBolt",
    affinityWeapons: ["holyBolt", "radiantBurst", "garlicAura", "holySmash"],
    color: "#9fe3b0",
    glyph: "P",
    strength: "Divine light that outlasts darkness — heal specialist",
    weakness: "Weakest weapon damage",
  },
  warlock: {
    id: "warlock",
    name: "Warlock",
    maxHp: 75,
    speed: 95,
    startingWeapon: "fireBolt",
    affinityWeapons: ["fireBolt", "lifeDrain", "poisonFlask", "shadowDaggers"],
    color: "#9b6bff",
    glyph: "W",
    strength: "Life-stealing dark caster — 8% lifesteal on damage dealt",
    weakness: "Fragile body; must stay aggressive to survive",
  },
  elf: {
    id: "elf",
    name: "Elf",
    maxHp: 90,
    speed: 100,
    startingWeapon: "swordSweep",
    startingWeapons: ["swordSweep", "fireBolt"],
    weaponSlotCap: 3,
    affinityWeapons: ["swordSweep", "fireBolt", "magicArrow", "frostNova"],
    color: "#7dcea0",
    glyph: "E",
    strength: "Graceful blade-and-spell duelist — starts with both tools",
    weakness: "Weapon slots 4→3; neither parent's peak damage or toughness",
  },
  thief: {
    id: "thief",
    name: "Thief",
    maxHp: 85,
    speed: 115,
    startingWeapon: "throwingAxe",
    affinityWeapons: ["throwingAxe", "shadowDaggers", "poisonFlask", "crossbowBolt"],
    color: "#d478a0",
    glyph: "T",
    strength: "Untouchable blur — crit 20%×2, magnet +60px, gold +20%",
    weakness: "Low HP; DPS collapses when crits miss",
  },
  monk: {
    id: "monk",
    name: "Monk",
    maxHp: 110,
    speed: 100,
    startingWeapon: "garlicAura",
    weaponSlotCap: 1,
    affinityWeapons: ["garlicAura"],
    color: "#e8c89a",
    glyph: "O",
    strength: "One weapon perfected to Lv.8, contact damage −20%",
    weakness: "Weapon slots locked to 1 — no ranged options ever",
  },
};

export const weaponDefinitions: Record<WeaponId, WeaponDefinition> = {
  swordSweep: {
    id: "swordSweep",
    name: "Sword Sweep",
    damage: 8,
    cooldownTicks: Math.round(0.9 * TICKS_PER_SECOND),
    range: 70,
    radius: 70,
    projectileSpeed: 0,
    flavor: "damage",
  },
  fireBolt: {
    id: "fireBolt",
    name: "Fire Bolt",
    damage: 12,
    cooldownTicks: Math.round(1.1 * TICKS_PER_SECOND),
    range: 260,
    radius: 5,
    projectileSpeed: 260,
    flavor: "damage",
  },
  holyBolt: {
    id: "holyBolt",
    name: "Holy Bolt",
    damage: 7,
    cooldownTicks: TICKS_PER_SECOND,
    range: 240,
    radius: 5,
    projectileSpeed: 230,
    flavor: "defense",
  },
  throwingAxe: {
    id: "throwingAxe",
    name: "Throwing Axe",
    damage: 15,
    cooldownTicks: Math.round(1.6 * TICKS_PER_SECOND),
    range: 230,
    radius: 8,
    projectileSpeed: 210,
    flavor: "damage",
  },
  frostNova: {
    id: "frostNova",
    name: "Frost Nova",
    damage: 6,
    cooldownTicks: Math.round(2.5 * TICKS_PER_SECOND),
    range: 90,
    radius: 90,
    projectileSpeed: 0,
    flavor: "defense",
  },
  garlicAura: {
    id: "garlicAura",
    name: "Garlic Aura",
    damage: 2,
    cooldownTicks: Math.round(0.5 * TICKS_PER_SECOND),
    range: 80,
    radius: 80,
    projectileSpeed: 0,
    flavor: "focus",
  },
  holySmash: {
    id: "holySmash",
    name: "Holy Smash",
    damage: 14,
    cooldownTicks: Math.round(1.4 * TICKS_PER_SECOND),
    range: 85,
    radius: 55,
    projectileSpeed: 0,
    flavor: "damage",
  },
  lifeDrain: {
    id: "lifeDrain",
    name: "Life Drain",
    damage: 9,
    cooldownTicks: Math.round(1.2 * TICKS_PER_SECOND),
    range: 200,
    radius: 6,
    projectileSpeed: 280,
    flavor: "damage",
  },
  shadowDaggers: {
    id: "shadowDaggers",
    name: "Shadow Daggers",
    damage: 6,
    cooldownTicks: Math.round(1.3 * TICKS_PER_SECOND),
    range: 210,
    radius: 4,
    projectileSpeed: 240,
    flavor: "damage",
  },
  earthShatter: {
    id: "earthShatter",
    name: "Earth Shatter",
    damage: 11,
    cooldownTicks: Math.round(2.2 * TICKS_PER_SECOND),
    range: 100,
    radius: 100,
    projectileSpeed: 0,
    flavor: "damage",
  },
  magicArrow: {
    id: "magicArrow",
    name: "Magic Arrow",
    damage: 10,
    cooldownTicks: Math.round(1.0 * TICKS_PER_SECOND),
    range: 280,
    radius: 5,
    projectileSpeed: 250,
    flavor: "damage",
  },
  whirlwindAxe: {
    id: "whirlwindAxe",
    name: "Whirlwind Axe",
    damage: 7,
    cooldownTicks: Math.round(1.5 * TICKS_PER_SECOND),
    range: 95,
    radius: 95,
    projectileSpeed: 0,
    flavor: "damage",
  },
  shieldBash: {
    id: "shieldBash",
    name: "Shield Bash",
    damage: 9,
    cooldownTicks: Math.round(1.5 * TICKS_PER_SECOND),
    range: 75,
    radius: 70,
    projectileSpeed: 0,
    flavor: "defense",
  },
  radiantBurst: {
    id: "radiantBurst",
    name: "Radiant Burst",
    damage: 8,
    cooldownTicks: Math.round(2.0 * TICKS_PER_SECOND),
    range: 110,
    radius: 110,
    projectileSpeed: 0,
    flavor: "defense",
  },
  meteor: {
    id: "meteor",
    name: "Meteor",
    damage: 28,
    cooldownTicks: Math.round(3.5 * TICKS_PER_SECOND),
    range: 220,
    radius: 70,
    projectileSpeed: 0,
    flavor: "damage",
  },
  chainLightning: {
    id: "chainLightning",
    name: "Chain Lightning",
    damage: 10,
    cooldownTicks: Math.round(1.8 * TICKS_PER_SECOND),
    range: 240,
    radius: 6,
    projectileSpeed: 320,
    flavor: "damage",
  },
  poisonFlask: {
    id: "poisonFlask",
    name: "Poison Flask",
    damage: 4,
    cooldownTicks: Math.round(2.0 * TICKS_PER_SECOND),
    range: 180,
    radius: 50,
    projectileSpeed: 180,
    flavor: "damage",
  },
  crossbowBolt: {
    id: "crossbowBolt",
    name: "Crossbow Bolt",
    damage: 13,
    cooldownTicks: Math.round(1.35 * TICKS_PER_SECOND),
    range: 300,
    radius: 4,
    projectileSpeed: 340,
    flavor: "damage",
  },
};

export const passiveDefinitions: Record<PassiveId, PassiveDefinition> = {
  maxHp: { id: "maxHp", name: "+Max HP 20%", flavor: "defense" },
  speed: { id: "speed", name: "+Speed 12%", flavor: "speed" },
  damage: { id: "damage", name: "+Damage 15%", flavor: "damage" },
  magnet: { id: "magnet", name: "Magnet +60px", flavor: "economy" },
  gold: { id: "gold", name: "Gold +20%", flavor: "economy" },
};

export const dialogLines: Record<OptionFlavor, readonly string[]> = {
  damage: [
    "For the crowd!",
    "My blade drinks the roar.",
    "Let the sand learn fire.",
  ],
  economy: [
    "Spoils for the victor.",
    "Every coin has a witness.",
    "The crowd pays in gold.",
  ],
  defense: [
    "I will not die on this sand.",
    "Shield high. Eyes forward.",
    "Stone outlasts the cheer.",
  ],
  speed: [
    "Fast feet shame the grave.",
    "I move before they chant.",
    "The arena cannot hold me.",
  ],
  focus: [
    "One form. One finish.",
    "Again, for the stands.",
    "Discipline wins the sand.",
  ],
};

export type EnemyDefinition = {
  readonly kind: EnemyKind;
  readonly hp: number;
  readonly speed: number;
  readonly damage: number;
  readonly radius: number;
};

export const enemyDefinitions: Record<EnemyKind, EnemyDefinition> = {
  slime: { kind: "slime", hp: 10, speed: 40, damage: 4, radius: 11 },
  bat: { kind: "bat", hp: 6, speed: 85, damage: 3, radius: 9 },
  brute: { kind: "brute", hp: 40, speed: 48, damage: 8, radius: 15 },
  eliteBrute: { kind: "eliteBrute", hp: 150, speed: 55, damage: 12, radius: 18 },
};
